# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "Kubernetes Connection Manager CLI"
  homepage "https://github.com/jessesanford/kconnect"
  version "0.5.3-rc.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessesanford/kconnect/releases/download/0.5.3-rc.1/kconnect_macos_amd64.tar.gz"
      sha256 "2b847feecd1547ec474ae517afb84a7e5163248ffc10268c1b709a1f61fec223"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessesanford/kconnect/releases/download/0.5.3-rc.1/kconnect_macos_arm64.tar.gz"
      sha256 "3a0c22671a135722f04b8f765be6cd6b9a3da92e2b71ba023f60ffafac049500"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jessesanford/kconnect/releases/download/0.5.3-rc.1/kconnect_linux_amd64.tar.gz"
      sha256 "401b43f2dcd543a74a6c1eeb86c7f7c35d5692b2e6cac06ed4326d6b379e687d"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jessesanford/kconnect/releases/download/0.5.3-rc.1/kconnect_linux_arm.tar.gz"
      sha256 "fe03695f91ade1670e002d81d82dec206f0783bc327f111974f76c565eaf810b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessesanford/kconnect/releases/download/0.5.3-rc.1/kconnect_linux_arm64.tar.gz"
      sha256 "ef7a6905b411702a6a83031d4ae36d475ce0c84d28d97dcad92344513f09ee5b"
    end
  end

  depends_on "aws-iam-authenticator"
  depends_on "Azure/kubelogin/kubelogin"
  depends_on "kubernetes-cli"

  def install
    bin.install "kconnect"
  end
end
